import {describe,expect,it} from 'vitest';
import {cryptoRandomIndex,isThemeSelectionValid,toggleTalentSelection,toggleThemeSelection} from '../src/domain/generators';
import {extractJson,validateFamilies,validateProgressionSystem,validateTalents} from '../src/ai/provider';
describe('AI 响应解析',()=>{it('解析代码块与前后说明中的JSON',()=>{expect(extractJson('```json\n["甲","乙"]\n```')).toEqual(['甲','乙']);expect(extractJson('以下是结果： {"name":"世界"} 谢谢')).toEqual({name:'世界'})});it('拒绝无JSON',()=>expect(()=>extractJson('无')).toThrow())});
describe('家庭/天赋严格验证',()=>{const f=(label:string)=>({label,parents:'父母',socialClass:'普通',location:'城',advantages:['爱'],risks:['压力'],hiddenSecret:'秘密'});it('只接受三个完整且同批组合不同的家庭',()=>{expect(validateFamilies([f('甲'),f('乙'),f('丙')],'modern-city')).toHaveLength(3);expect(()=>validateFamilies([f('甲'),f('甲'),f('丙')],'modern-city')).toThrow('互不重复');expect(()=>validateFamilies([f('甲')],'modern-city')).toThrow('恰好 3')});it('只接受10个唯一天赋',()=>{expect(validateTalents(Array.from({length:10},(_,i)=>`天赋${i}`))).toHaveLength(10);expect(()=>validateTalents(Array(10).fill('重复'))).toThrow()})});
describe('加密随机索引',()=>{it('始终处于范围',()=>{for(let i=0;i<100;i++)expect(cryptoRandomIndex(3)).toBeGreaterThanOrEqual(0),expect(cryptoRandomIndex(3)).toBeLessThan(3);expect(()=>cryptoRandomIndex(0)).toThrow()})});
describe('选择限制',()=>{it('主题3-5',()=>{let x:string[]=[];for(const t of ['a','b','c','d','e','f'])x=toggleThemeSelection(x,t);expect(x).toHaveLength(5);expect(isThemeSelectionValid(x)).toBe(true)});it('天赋严格最多3',()=>expect(toggleTalentSelection(['a','b','c'],'d')).toEqual(['a','b','c']))});
describe('旧存档兼容',()=>{it('补齐新字段并移除旧 custom 投胎方式',async()=>{localStorage.setItem('fusheng-ai-life-state',JSON.stringify({birthMethod:'custom',character:{name:'旧',gender:'女',personality:'旧'},currentStep:'welcome'}));const {restoreState}=await import('../src/App');const x=restoreState();expect(x.birthAnswers).toEqual({});expect(x.familyRefreshCount).toBe(0);expect(x.talentRefreshCount).toBe(0);expect(x.character).toEqual({name:'旧',gender:'女'});localStorage.clear()})});

describe('成长体系严格校验',()=>{
 const make=(mode:string,years:number[])=>({name:'体系',unit:'点',description:'说明',lifespanMode:mode,tiers:years.map((y,i)=>({name:`层${i}`,requiredProgress:i*10,lifespan:{years:y,ageless:false,naturalDeathEnabled:true},description:'说明',advancementConditions:['条件'],risks:['风险']}))});
 it('接受四种合法寿命模式',()=>{expect(validateProgressionSystem(make('increasing',[10,20,20])).lifespanMode).toBe('increasing');expect(validateProgressionSystem(make('decreasing',[30,20,10])).lifespanMode).toBe('decreasing');expect(validateProgressionSystem(make('unchanged',[10,10,10])).lifespanMode).toBe('unchanged');expect(validateProgressionSystem(make('mixed',[10,30,20])).lifespanMode).toBe('mixed')});
 it('校验层数边界、首层进度和不老规则',()=>{expect(()=>validateProgressionSystem(make('increasing',[10,20]))).toThrow('3-12');expect(validateProgressionSystem(make('increasing',Array.from({length:12},(_,i)=>10+i))).tiers).toHaveLength(12);expect(()=>validateProgressionSystem(make('increasing',Array.from({length:13},(_,i)=>10+i)))).toThrow('3-12');const bad=make('increasing',[10,20,30]);bad.tiers[0].requiredProgress=1;expect(()=>validateProgressionSystem(bad)).toThrow();const ageless=make('increasing',[10,20,30]);ageless.tiers[1].lifespan.ageless=true;expect(()=>validateProgressionSystem(ageless)).toThrow('不老')});
 it('拒绝模式不符和 mixed 单调寿命',()=>{expect(()=>validateProgressionSystem(make('increasing',[30,20,40]))).toThrow('模式');expect(()=>validateProgressionSystem(make('mixed',[10,20,30]))).toThrow('模式')});
});

import {rankFamilies,sampleFamilies} from '../src/domain/generators';
describe('预生成家庭池本地选择',()=>{const pool=Array.from({length:12},(_,i)=>({id:`f${i}`,worldId:'modern-city' as const,label:i===7?'温暖之家':`家庭${i}`,parents:'父母',socialClass:'普通',location:'城',advantages:i===7?['温暖陪伴']:['稳定'],risks:['压力'],hiddenSecret:'秘密'}));it('本地抽样互不重复且不改变稳定ID',()=>{const cards=sampleFamilies(pool,3);expect(new Set(cards.map(x=>x.id)).size).toBe(3);expect(cards.every(x=>pool.some(p=>p.id===x.id))).toBe(true)});it('问答按AI预生成的适配标签排序家庭',()=>{const tagged=pool.map((x,i)=>({...x,birthFit:i===9?['渴望远行']:[]}));expect(rankFamilies(tagged,{path:'渴望远行'})[0].id).toBe('f9')})});
