import {describe,expect,it} from 'vitest';
import {advanceLife,checkNaturalDeath,chooseDynamicAdvanceMonths,createInitialLifeState,formatAge,getLifeStage,inferLifespanLimitMonths,normalizeLifeState} from '../src/life/engine';
import type {FamilyCard,GeneratedWorld} from '../src/types';
const family:FamilyCard={id:'f',worldId:'modern-city',label:'家',parents:'教师、医生',socialClass:'普通中产',location:'海城',advantages:['稳定'],risks:['忙碌'],hiddenSecret:'无'};
describe('人生阶段',()=>{it('覆盖所有月龄边界',()=>{expect([[0,'新生儿'],[11,'新生儿'],[12,'幼儿'],[35,'幼儿'],[36,'童年'],[143,'童年'],[144,'少年'],[215,'少年'],[216,'青年'],[359,'青年'],[360,'成年'],[719,'成年'],[720,'老年']].map(([n])=>getLifeStage(n as number))).toEqual(['新生儿','新生儿','幼儿','幼儿','童年','童年','少年','少年','青年','青年','成年','成年','老年'])});it('格式化年龄',()=>expect(formatAge(25)).toBe('2 岁 1 个月'))});
describe('人生初始化与推进',()=>{it('属性稳定、均在范围并生成家庭出生记录',()=>{const a=createInitialLifeState({family,talents:['敏锐','善良','坚韧'],characterName:'甲'}),b=createInitialLifeState({family,talents:['敏锐','善良','坚韧'],characterName:'甲'});expect(a.attributes).toEqual(b.attributes);expect(Object.values(a.attributes).every(x=>x>=0&&x<=100)).toBe(true);expect(a.familyMembers).toHaveLength(2);expect(a.familyMembers[0].occupation).toBe('教师');expect(a.timeline[0].kind).toBe('birth')});it('推进阶段、成员年龄、周岁时间线且不记录普通月',()=>{let s=createInitialLifeState({family,talents:['a']});s=advanceLife(s,6);expect(s.timeline).toHaveLength(1);const before=s.familyMembers[0].ageMonths;s=advanceLife(s,6);expect(s.ageMonths).toBe(12);expect(s.lifeStage).toBe('幼儿');expect(s.familyMembers[0].ageMonths).toBe(before+6);expect(s.timeline.map(x=>x.kind)).toEqual(['birth','stage','birthday']);expect(Object.values(s.vitals).every(x=>x>=0&&x<=100)).toBe(true)})});

const world=(lifespan:string,templateId:GeneratedWorld['templateId']='modern-city')=>({templateId,lifespan} as GeneratedWorld);
describe('动态寿命与时间',()=>{
 it('初始寿命由模板成长体系第0层决定',()=>{expect(inferLifespanLimitMonths(world('平均70-90年'))).toBe(85*12);expect(inferLifespanLimitMonths(world('可活数千年','cultivation'))).toBe(120*12)});
 it('普通各阶段及健康差会缩短',()=>{const s=createInitialLifeState({family,talents:[],generatedWorld:world('80年')});expect(chooseDynamicAdvanceMonths(s,world('80年'))).toBe(1);expect(chooseDynamicAdvanceMonths({...s,ageMonths:24,lifeStage:'幼儿'},world('80年'))).toBe(3);expect(chooseDynamicAdvanceMonths({...s,ageMonths:60,lifeStage:'童年'},world('80年'))).toBe(6);expect(chooseDynamicAdvanceMonths({...s,ageMonths:400,lifeStage:'成年'},world('80年'))).toBe(12);expect(chooseDynamicAdvanceMonths({...s,ageMonths:500,lifeStage:'成年',vitals:{...s.vitals,health:20}},world('80年'))).toBe(3)});
 it('修仙先以凡人尺度推进，旧存档按当前层重算寿命',()=>{const w=world('寿元数千年','cultivation'),s=createInitialLifeState({family,talents:[],generatedWorld:w});expect(s.lifespanLimitMonths).toBe(120*12);expect(chooseDynamicAdvanceMonths({...s,ageMonths:400,lifeStage:'成年'},w)).toBe(12);const old={...s,lifespanLimitMonths:36000,progression:undefined} as any;expect(normalizeLifeState(old,w).lifespanLimitMonths).toBe(120*12);expect(checkNaturalDeath({...s,ageMonths:s.lifespanLimitMonths},()=>1).alive).toBe(false)});
 it('长跨度时间线不会爆炸',()=>{const s=createInitialLifeState({family,talents:[],generatedWorld:world('1000年')});const next=advanceLife({...s,ageMonths:360,lifeStage:'成年'},600);expect(next.timeline.length).toBeLessThanOrEqual(7);expect(()=>advanceLife(s,601)).toThrow()});
});
