import {describe,expect,it} from 'vitest';
import {advanceLife,applyEventChoice,checkNaturalDeath,createInitialLifeState,parseFamilyMembers,validateEffects,validateLifeEvent} from '../src/life/engine';
import type {FamilyCard} from '../src/types';
const family:FamilyCard={id:'f',worldId:'modern-city',label:'家',parents:'母亲是医生，父亲是高校讲师',socialClass:'普通',location:'城',advantages:['爱'],risks:['忙'],hiddenSecret:'无'};
const initial=()=>createInitialLifeState({family,talents:['善良']});
describe('家庭解析',()=>{it('按角色绑定职业且不强制双亲',()=>{expect(parseFamilyMembers(family.parents)).toEqual([{role:'母亲',name:'母亲',occupation:'医生'},{role:'父亲',name:'父亲',occupation:'高校讲师'}]);expect(parseFamilyMembers('养母是画家')).toHaveLength(1);expect(parseFamilyMembers('王阿姨')).toEqual([{role:'监护人',name:'监护人',occupation:'王阿姨'}]);expect(parseFamilyMembers('孤身一人，无人照料')).toEqual([])})});
describe('效果与事件',()=>{it('白名单限幅且拒绝路径',()=>{const s=initial();expect(validateEffects([{type:'modify_vital',vital:'health',amount:-99},{type:'modify_attribute',attribute:'luck',amount:50},{type:'hack',path:'alive'}],s)).toEqual([{type:'modify_vital',vital:'health',amount:-20},{type:'modify_attribute',attribute:'luck',amount:10}])});it('应用、新角色、NPC与玩家死亡',()=>{let s=advanceLife(initial(),1);s.pendingEvent=validateLifeEvent({category:'family',title:'相遇',description:'一天',participants:[],choices:[{id:'a',label:'交谈',intent:'友善',effects:[{type:'add_character',character:{name:'小林',role:'朋友'}},{type:'kill_character',memberId:'family-1'}]},{id:'b',label:'离开',intent:'回避',effects:[{type:'kill_player',reason:'危险'}]}]},s,1);let a=applyEventChoice(s,'a',()=>.5);expect(a.socialCharacters[0].name).toBe('小林');expect(a.familyMembers[0].alive).toBe(false);s.pendingEvent=validateLifeEvent({category:'danger',title:'险境',description:'危险',participants:[],choices:[{id:'a',label:'承受',intent:'',effects:[{type:'kill_player'}]},{id:'b',label:'逃',intent:'',effects:[{type:'modify_vital',vital:'stress',amount:-1}]}]},s,1);expect(applyEventChoice(s,'a',()=>.5).alive).toBe(false)})});
describe('推进与死亡',()=>{it('pending 阻止推进，生成失败可保留原对象',()=>{const s=initial();const advanced=advanceLife(s,1);advanced.pendingEvent={} as any;expect(()=>advanceLife(advanced,1)).toThrow();expect(s.ageMonths).toBe(0)});it('当前层级寿命到期必死且随机可注入',()=>{let s=initial();s={...s,ageMonths:s.lifespanLimitMonths,lifeStage:'老年'};expect(checkNaturalDeath(s,()=>1).alive).toBe(false);s={...initial(),ageMonths:600,lifeStage:'成年',vitals:{...initial().vitals,health:1}};expect(checkNaturalDeath(s,()=>0).alive).toBe(false)})});
describe('成长体系事件',()=>{
 it('进度达标只设置待突破，不自动升级',()=>{let s=advanceLife(initial(),1);const oldLimit=s.lifespanLimitMonths;s.pendingEvent=validateLifeEvent({category:'growth',title:'修行',description:'积累',participants:[],choices:[{id:'a',label:'积累',intent:'成长',effects:[{type:'modify_progression',amount:100}]},{id:'b',label:'休息',intent:'稳定',effects:[{type:'modify_vital',vital:'energy',amount:2}]}]},s,1);const next=applyEventChoice(s,'a',()=>.5);expect(next.progression.tierIndex).toBe(0);expect(next.progression.pendingBreakthrough).toBe(true);expect(next.lifespanLimitMonths).toBe(oldLimit)});
 it('突破事件要求每项尝试，普通事件拒绝尝试',()=>{const ordinary=advanceLife(initial(),1),payload={category:'growth',title:'突破',description:'关口',participants:[],choices:[{id:'a',label:'稳',intent:'',effects:[{type:'attempt_breakthrough',risk:'safe'}]},{id:'b',label:'险',intent:'',effects:[{type:'attempt_breakthrough',risk:'reckless'}]}]};expect(()=>validateLifeEvent(payload,ordinary,1)).toThrow('普通事件');const pending={...ordinary,progression:{...ordinary.progression,pendingBreakthrough:true}};expect(validateLifeEvent(payload,pending,1).eventType).toBe('breakthrough');expect(()=>validateLifeEvent({...payload,choices:[{id:'a',label:'空',intent:'',effects:[]},{id:'b',label:'险',intent:'',effects:[{type:'attempt_breakthrough',risk:'reckless'}]}]},pending,1)).toThrow('每个选项')});
 it('突破成功与失败均由注入随机数裁决',()=>{let s=advanceLife(initial(),1);s={...s,progression:{...s.progression,progress:60,pendingBreakthrough:true}};const payload={category:'growth',title:'突破',description:'关口',participants:[],choices:[{id:'a',label:'稳',intent:'',effects:[{type:'attempt_breakthrough',risk:'safe'}]},{id:'b',label:'险',intent:'',effects:[{type:'attempt_breakthrough',risk:'reckless'}]}]};s.pendingEvent=validateLifeEvent(payload,s,1);const success=applyEventChoice(s,'a',()=>0);expect(success.progression.tierIndex).toBe(1);expect(success.progression.pendingBreakthrough).toBe(false);const failed=applyEventChoice(s,'a',()=>.99);expect(failed.progression.tierIndex).toBe(0);expect(failed.vitals.health).toBeLessThan(s.vitals.health);expect(failed.progression.progress).toBeLessThan(failed.progression.nextTierProgress!)});
 it('不老层不自然死亡但事件仍可杀死玩家',()=>{let s=initial();s={...s,currentLifespanRule:{years:1,ageless:true,naturalDeathEnabled:false},lifespanLimitMonths:12,ageMonths:120};expect(checkNaturalDeath(s,()=>0).alive).toBe(true);s.pendingEvent=validateLifeEvent({category:'danger',title:'灾难',description:'致命',participants:[],choices:[{id:'a',label:'死',intent:'',effects:[{type:'kill_player'}]},{id:'b',label:'避',intent:'',effects:[{type:'modify_vital',vital:'stress',amount:-2}]}]},s,1);expect(applyEventChoice(s,'a',()=>0).alive).toBe(false)});
});

describe('事件有效效果与中文摘要',()=>{it('拒绝无有效本地效果的选项并记录中文变化',()=>{const s=advanceLife(initial(),3);expect(()=>validateLifeEvent({category:'health',title:'空事件',description:'无',participants:[],choices:[{id:'a',label:'空',intent:'',effects:[]},{id:'b',label:'也是空',intent:'',effects:[{type:'unknown'}]}]},s,3)).toThrow('没有有效的本地效果');const event=validateLifeEvent({category:'health',title:'休养',description:'恢复',participants:[],choices:[{id:'a',label:'休息',intent:'恢复',effects:[{type:'modify_vital',vital:'health',amount:2}]},{id:'b',label:'散步',intent:'放松',effects:[{type:'modify_vital',vital:'stress',amount:-2}]}]},s,3);const state=applyEventChoice({...s,pendingEvent:event},'a',()=>.5);expect(state.timeline[state.timeline.length-1]?.effectsSummary?.[0]).toMatch(/^健康 /)})});
