import type {AiProvider,AiSettings,EventResolution,FamilyCard,FamilyGenerationRequest,GeneratedWorld,LifeEventGenerationContext,NarrativeContext,PendingLifeEvent,ProgressionSystem,TalentGenerationRequest,WorldDefinition,WorldGenerationRequest} from '../types';
import {cryptoRandomIndex} from '../domain/generators';
import {validateLifeEvent} from '../life/engine';
export function validateProgressionSystem(x:any):ProgressionSystem{const modes=['increasing','decreasing','mixed','unchanged'];if(!x||typeof x!=='object'||typeof x.name!=='string'||!x.name.trim()||typeof x.unit!=='string'||!x.unit.trim()||typeof x.description!=='string'||!x.description.trim()||!modes.includes(x.lifespanMode)||!Array.isArray(x.tiers)||x.tiers.length<3||x.tiers.length>12)throw new Error('AI 返回的成长体系 progressionSystem 缺失或格式错误（须为3-12层）');let last=-1;const tiers=x.tiers.map((t:any,i:number)=>{const life=t?.lifespan;if(!t||typeof t.name!=='string'||!t.name.trim()||typeof t.description!=='string'||!t.description.trim()||!Number.isFinite(t.requiredProgress)||t.requiredProgress<0||t.requiredProgress<=last||(i===0&&t.requiredProgress!==0)||!life||!Number.isFinite(life.years)||life.years<1||life.years>100000||typeof life.ageless!=='boolean'||typeof life.naturalDeathEnabled!=='boolean'||!Array.isArray(t.advancementConditions)||t.advancementConditions.some((v:any)=>typeof v!=='string'||!v.trim())||!Array.isArray(t.risks)||t.risks.some((v:any)=>typeof v!=='string'||!v.trim()))throw new Error(`成长体系第 ${i+1} 层无效`);if(life.ageless&&life.naturalDeathEnabled)throw new Error(`成长体系第 ${i+1} 层不老时不能启用自然死亡`);last=t.requiredProgress;return {name:t.name.trim(),requiredProgress:Math.round(t.requiredProgress),lifespan:{years:Math.round(life.years),ageless:life.ageless,naturalDeathEnabled:life.naturalDeathEnabled},description:t.description.trim(),advancementConditions:t.advancementConditions.map((v:string)=>v.trim()),risks:t.risks.map((v:string)=>v.trim())}});const ys=tiers.map((t:ProgressionSystem['tiers'][number])=>t.lifespan.years);const hasIncrease=ys.some((v:number,i:number)=>i>0&&v>ys[i-1]),hasDecrease=ys.some((v:number,i:number)=>i>0&&v<ys[i-1]);if(x.lifespanMode==='increasing'&&hasDecrease||x.lifespanMode==='decreasing'&&hasIncrease||x.lifespanMode==='unchanged'&&(hasIncrease||hasDecrease)||x.lifespanMode==='mixed'&&!(hasIncrease&&hasDecrease))throw new Error(`成长体系寿命不符合 ${x.lifespanMode} 模式`);return {name:x.name.trim(),unit:x.unit.trim(),description:x.description.trim(),lifespanMode:x.lifespanMode,tiers}}



export function extractJson(text:string):unknown{
 const clean=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');
 try{return JSON.parse(clean)}catch{/* extract below */}
 const starts=[clean.indexOf('{'),clean.indexOf('[')].filter(x=>x>=0).sort((a,b)=>a-b);
 if(!starts.length)throw new Error('AI 响应中没有找到 JSON');
 const start=starts[0], open=clean[start], close=open==='{'?'}':']'; let depth=0,inString=false,escaped=false;
 for(let i=start;i<clean.length;i++){const c=clean[i];if(inString){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')inString=false;continue}if(c==='"'){inString=true;continue}if(c===open)depth++;if(c===close&&--depth===0)return JSON.parse(clean.slice(start,i+1))}
 throw new Error('AI 返回的 JSON 不完整');
}
function contentOf(data:any,format:AiSettings['format']){const value=format==='anthropic'?data?.content?.find((x:any)=>x.type==='text')?.text:data?.choices?.[0]?.message?.content;if(typeof value!=='string'||!value.trim())throw new Error(data?.error?.message||'AI 没有返回文本内容');return value}
export function normalizeAiUrl(endpoint:string,format:AiSettings['format'],kind:'chat'|'models'){
 let base=endpoint.trim().replace(/\/+$/,'');
 const known=format==='anthropic'?['messages','models']:['chat/completions','models'];
 for(const suffix of known){const re=new RegExp(`/${suffix.replace('/','\\/')}/*$`,'i');base=base.replace(re,'')}
 return `${base}/${kind==='models'?'models':format==='anthropic'?'messages':'chat/completions'}`;
}
export function parseModelList(data:unknown):string[]{
 const source=Array.isArray(data)?data:(data&&typeof data==='object'&&(Array.isArray((data as any).data)?(data as any).data:Array.isArray((data as any).models)?(data as any).models:[]));
 const names=source.map((item:unknown)=>typeof item==='string'?item:item&&typeof item==='object'?(item as any).id??(item as any).name:'').filter((x:unknown):x is string=>typeof x==='string'&&Boolean(x.trim())).map((x:string)=>x.trim());
 return [...new Set<string>(names)].sort((a,b)=>a.localeCompare(b));
}
export function validateFamilies(value:unknown,worldId:FamilyCard['worldId'],expected=3,idPrefix=`ai-family-${Date.now()}`):FamilyCard[]{
 if(!Array.isArray(value)||value.length!==expected)throw new Error(`AI 必须返回恰好 ${expected} 个家庭`);
 const fields=['label','parents','socialClass','location','hiddenSecret'] as const;
 const cards=value.map((x:any,i)=>{const missing:string[]=[];if(!x||typeof x!=='object')missing.push('家庭对象');else{for(const k of fields)if(typeof x[k]!=='string'||!x[k].trim())missing.push(k);if(!Array.isArray(x.advantages)||!x.advantages.length||x.advantages.some((v:any)=>typeof v!=='string'||!v.trim()))missing.push('advantages');if(!Array.isArray(x.risks)||!x.risks.length||x.risks.some((v:any)=>typeof v!=='string'||!v.trim()))missing.push('risks');if(!Array.isArray(x.householdMembers)||x.householdMembers.some((m:any)=>!m||typeof m.name!=='string'||!m.name.trim()||typeof m.role!=='string'||!m.role.trim()||typeof m.occupation!=='string'||!m.occupation.trim()||!Number.isFinite(m.ageYears)||m.ageYears<0||m.ageYears>100000))missing.push('householdMembers');if(!Number.isFinite(x.startingWealth)||x.startingWealth<0||x.startingWealth>1e12)missing.push('startingWealth')}if(missing.length)throw new Error(`第 ${i+1} 个家庭结构不完整：${missing.join('、')}`);return {id:`${idPrefix}-${i+1}`,worldId,label:x.label.trim(),parents:x.parents.trim(),socialClass:x.socialClass.trim(),location:x.location.trim(),advantages:x.advantages.map((v:string)=>v.trim()),risks:x.risks.map((v:string)=>v.trim()),hiddenSecret:x.hiddenSecret.trim(),householdMembers:x.householdMembers.map((m:any)=>({name:m.name.trim(),role:m.role.trim(),occupation:m.occupation.trim(),ageYears:Math.round(m.ageYears)})),startingWealth:Math.round(x.startingWealth)}});
 const keys=cards.map(x=>`${x.label}\u0000${x.parents}\u0000${x.location}`);if(new Set(keys).size!==expected)throw new Error('同批家庭的名称、父母与地点组合必须互不重复');return cards;
}
export function validateTalents(value:unknown):string[]{if(!Array.isArray(value))throw new Error('天赋必须是 JSON 数组');const values=value.map(x=>typeof x==='string'?x.trim():'').filter(Boolean);if(values.length!==10||new Set(values).size!==10)throw new Error('AI 必须返回恰好 10 个互不重复的天赋');return values}
export const DEFAULT_MAX_TOKENS = 8192;
export const DEFAULT_TEMPERATURE = 0.7;

export function buildChatBody(s:AiSettings,system:string,user:string,maxTokens=s.maxTokens){
 const body:any=s.format==='anthropic'?{model:s.model,system,messages:[{role:'user',content:user}]}:{model:s.model,messages:[{role:'system',content:system},{role:'user',content:user}]};
 body.max_tokens=maxTokens??DEFAULT_MAX_TOKENS;
 body.temperature=s.temperature??DEFAULT_TEMPERATURE;
 return body;
}
export class RemoteAiProvider implements AiProvider{
 id='user-configured-ai'; constructor(private settings:AiSettings){}
 private headers(){const s=this.settings;const headers:Record<string,string>={'Content-Type':'application/json'};if(s.format==='anthropic'){headers['x-api-key']=s.apiKey;headers['anthropic-version']='2023-06-01'}else headers.Authorization=`Bearer ${s.apiKey}`;return headers}
 private async chat(system:string,user:string,maxTokens=this.settings.maxTokens){
  const s=this.settings;
  let response:Response;try{response=await fetch(normalizeAiUrl(s.endpoint,s.format,'chat'),{method:'POST',headers:this.headers(),body:JSON.stringify(buildChatBody(s,system,user,maxTokens))})}catch(e){throw new Error(`网络请求失败：${e instanceof Error?e.message:String(e)}`)}
  const raw=await response.text();let data:any;try{data=JSON.parse(raw)}catch{throw new Error(`API 返回非 JSON（HTTP ${response.status}）`)}if(!response.ok)throw new Error(data?.error?.message||`API 请求失败（HTTP ${response.status}）`);return contentOf(data,s.format)
 }
 async listModels(){let response:Response;try{response=await fetch(normalizeAiUrl(this.settings.endpoint,this.settings.format,'models'),{headers:this.headers()})}catch(e){throw new Error(`拉取模型失败：${e instanceof Error?e.message:String(e)}`)}const raw=await response.text();let data:any;try{data=JSON.parse(raw)}catch{throw new Error(`模型接口返回非 JSON（HTTP ${response.status}）`)}if(!response.ok)throw new Error(data?.error?.message||`拉取模型失败（HTTP ${response.status}）`);const models=parseModelList(data);if(!models.length)throw new Error('模型接口未返回可识别的模型');return models}
 async testConnection(){const result=await this.chat('你是连接测试助手。','只回复“连接成功”。',this.settings.maxTokens===undefined?32:Math.min(this.settings.maxTokens,32));return result.trim()}
 async generateThemeTags(template:WorldDefinition,customPrompt=''){
  const creativeNonce=`${Date.now()}-${crypto.getRandomValues(new Uint32Array(2)).join('-')}`;
  const brief={templateName:template.name,worldBoundary:template.description,tone:template.atmosphere,referenceDimensions:template.keywords,customPrompt};
  const text=await this.chat(
   '你是富有创造力的人生模拟器世界设计师。必须仅返回 JSON 字符串数组，不要解释。每次请求都要重新构思，不能输出固定标签表。',
   `请为这个世界模板即兴生成严格恰好10个互不重复的中文主题标签，供玩家选择3到5个。\n要求：\n1. 每个标签2到6个汉字；\n2. 严格10项中，约5到6项要形成两组明显关联的主题，每组约2到3项；同组主题被玩家选中后，应能自然串成一条连续人生主线或层层推进的矛盾链；\n3. 其余约4到5项应彼此相对独立，也与两组主线保持距离，用于制造支线、偶遇和意外转折；\n4. 标签文字本身绝对不要出现组号、分组、主线、支线等说明，也不要输出嵌套数组或对象；\n5. 十项整体覆盖情感关系、家庭或身份、成长场景、职业或生存道路、社会矛盾、危险秘密等维度；至少6项必须结合本次世界重新创造，不得机械照抄参考词；\n6. 同一模板重复请求时应产生明显不同的组合；所有标签必须符合模板边界，现代都市不能出现修仙，古代王朝不能出现互联网；\n7. 最终仍只输出一个合法JSON字符串数组，严格恰好10个互不重复的字符串，不要任何解释。\n本次创作扰动码：${creativeNonce}\n模板边界：${JSON.stringify(brief)}`
  );
  const value=extractJson(text);if(!Array.isArray(value))throw new Error('主题标签必须是 JSON 数组');const tags=[...new Set(value.filter(x=>typeof x==='string').map(x=>x.trim()).filter(Boolean))];if(tags.length!==10)throw new Error(`AI 必须返回恰好 10 个不同标签，实际为 ${tags.length} 个`);return tags
 }
 async generateWorld(req:WorldGenerationRequest):Promise<GeneratedWorld>{
  const nonce=`${Date.now()}-${crypto.getRandomValues(new Uint32Array(2)).join('-')}`;
  const templateBrief={id:req.template.id,name:req.template.name,headline:req.template.headline,description:req.template.description,eraTag:req.template.eraTag,atmosphere:req.template.atmosphere,worldRules:req.template.detailSections,customPrompt:req.customPrompt};
  // Step 1: establish only the world's immutable core, keeping the response compact and reliable.
  const coreText=await this.chat('你是严谨而富有原创性的世界构建器。只返回合法JSON对象。',`推演一个全新、自洽、适合模拟完整人生的世界。只生成世界核心，不要生成成长体系、问题或家庭。必须包含非空字符串 name,eraBackground,socialStructure,coreConflict,livingEnvironment,growthPaths,loveMarriageRules,familyStructure,dangers,lifespan,overview，以及至少4项的非空字符串数组 birthRegions，并包含 attributeLabels 对象，必须严格提供 physique,intelligence,charisma,willpower,creativity,social,morality,luck 八个键，每个值是1-8个汉字、符合本世界观且互不重复的属性显示名。世界名称、制度、地区和矛盾必须具体原创。\n扰动码：${nonce}\n世界边界：${JSON.stringify(templateBrief)}\n玩家主题：${JSON.stringify(req.selectedThemes)}`);
  const x=extractJson(coreText) as any,fields=['name','eraBackground','socialStructure','coreConflict','livingEnvironment','growthPaths','loveMarriageRules','familyStructure','dangers','lifespan','overview'];
  if(!x||typeof x!=='object'||fields.some(k=>typeof x[k]!=='string'||!x[k].trim())||!Array.isArray(x.birthRegions)||x.birthRegions.length<4||x.birthRegions.some((v:any)=>typeof v!=='string'||!v.trim()))throw new Error('AI 返回的世界核心字段缺失或格式错误');const attributeKeys=['physique','intelligence','charisma','willpower','creativity','social','morality','luck'] as const;if(!x.attributeLabels||attributeKeys.some(k=>typeof x.attributeLabels[k]!=='string'||!x.attributeLabels[k].trim()||x.attributeLabels[k].trim().length>8)||new Set(attributeKeys.map(k=>x.attributeLabels[k].trim())).size!==8)throw new Error('AI 返回的世界属性名称不完整或重复');const attributeLabels=Object.fromEntries(attributeKeys.map(k=>[k,x.attributeLabels[k].trim()])) as GeneratedWorld['attributeLabels'];
  const generatedAt=new Date().toISOString(),core={templateId:req.template.id,selectedThemes:req.selectedThemes,generatedAt,...Object.fromEntries(fields.map(k=>[k,x[k].trim()])),birthRegions:x.birthRegions.map((v:string)=>v.trim()),attributeLabels};
  // Step 2: progression is generated and validated independently.
  const progressionText=await this.chat('你是严谨的成长体系设计师。只返回合法JSON对象。',`根据世界设计成长体系：{name,unit,description,lifespanMode,tiers}。lifespanMode为increasing/decreasing/mixed/unchanged；tiers严格3-12层，每层含name,requiredProgress,lifespan:{years,ageless,naturalDeathEnabled},description,advancementConditions:string[],risks:string[]。首层进度0且严格递增，years为1-100000，寿命序列遵循模式，ageless时naturalDeathEnabled=false。资料：${JSON.stringify(core)}`);
  const progressionSystem=validateProgressionSystem(extractJson(progressionText));
  // Step 3: questionnaire is world-specific but independent from the family pool.
  const questionsText=await this.chat('你是出生问答设计师。只返回合法JSON数组。',`根据世界设计严格4道互不重复的出生偏好问题。每项必须包含唯一非空key、非空title、严格4个互不重复的非空字符串options。问题应体现本世界独有的地区、阶层、家庭结构、资源和风险，不得使用固定通用题。资料：${JSON.stringify({...core,progressionSystem})}`);
  const q=extractJson(questionsText) as any;if(!Array.isArray(q)||q.length!==4)throw new Error('AI 必须返回恰好 4 个出生问答问题');
  const birthQuestions=q.map((item:any,i:number)=>{if(!item||typeof item.key!=='string'||!item.key.trim()||typeof item.title!=='string'||!item.title.trim()||!Array.isArray(item.options)||item.options.length!==4||item.options.some((v:any)=>typeof v!=='string'||!v.trim())||new Set(item.options).size!==4)throw new Error(`第 ${i+1} 个出生问题格式错误`);return {key:item.key.trim(),title:item.title.trim(),options:item.options.map((v:string)=>v.trim())}});if(new Set(birthQuestions.map((item:any)=>item.key)).size!==4)throw new Error('出生问题 key 必须唯一');
  const worldBrief={...core,progressionSystem,birthQuestions};
  // Steps 4-5: split 21 candidates into two smaller batches to reduce omissions and truncation.
  const generateBatch=async(count:number,batch:number,existing:string[]=[])=>{const prompt=`生成严格恰好${count}个家庭候选，只返回JSON数组。每项必须包含 label,parents,socialClass,location,advantages,risks,hiddenSecret,householdMembers,startingWealth。householdMembers是当前真实共同生活家庭成员数组，每项{name,role,occupation,ageYears}；确实孤身一人时必须为空数组，单亲家庭必须明确列出父亲或母亲，禁止虚构监护人。startingWealth是0至1000000000000的数字，必须符合家庭实际处境。advantages和risks必须是至少1项的非空字符串数组，其余文本字段必须是非空字符串。当前批及已有家庭的label+parents+location组合不得重复。覆盖不同地区、阶层、结构、资源、优势和风险；文字简洁，单个字符串尽量不超过40字。不得省略字段、不得使用null。世界资料：${JSON.stringify(worldBrief)}${existing.length?`\n不得重复已有组合：${JSON.stringify(existing)}`:''}`;const run=async(repair='')=>validateFamilies(extractJson(await this.chat('你是严格的家庭候选数据生成器。只返回合法JSON数组并逐项检查七个必填字段。',prompt+repair)),req.template.id,count,`world-family-${generatedAt}-b${batch}`);try{return await run()}catch(error){const reason=error instanceof Error?error.message:String(error);return run(`\n上次校验失败：${reason}。请重新完整生成本批全部${count}项。`)}};
  const first=await generateBatch(11,1),signatures=first.map(card=>`${card.label}|${card.parents}|${card.location}`),second=await generateBatch(10,2,signatures),familyPool=[...first,...second];
  const allKeys=familyPool.map(card=>`${card.label}\u0000${card.parents}\u0000${card.location}`);if(new Set(allKeys).size!==21)throw new Error('两批家庭之间存在重复，请重新推演世界');
  return {...worldBrief,familyPool} as GeneratedWorld;
 }
 async generateProgressionSystem(world:GeneratedWorld,template:WorldDefinition,selectedThemes:string[]):Promise<ProgressionSystem>{const text=await this.chat('你是严谨的成长体系设计师。只返回合法JSON对象。',`为已生成世界单独重新设计成长体系，不改变任何其他世界字段。严格结构：{name,unit,description,lifespanMode,tiers}，lifespanMode为increasing/decreasing/mixed/unchanged；tiers 3-12层，每层{name,requiredProgress,lifespan:{years,ageless,naturalDeathEnabled},description,advancementConditions:string[],risks:string[]}；首层进度0且严格递增，years 1-100000；寿命序列遵循模式；ageless时naturalDeathEnabled=false。资料：${JSON.stringify({world,template:{name:template.name,description:template.description},selectedThemes})}`);return validateProgressionSystem(extractJson(text))}
 async generateFamilies(r:FamilyGenerationRequest){const text=await this.chat('你是人生模拟器家庭生成器。仅返回合法JSON数组。',`严格生成3个结构完整且本批互不重复的家庭。每项字段：label,parents,socialClass,location,advantages(非空字符串数组),risks(非空字符串数组),hiddenSecret,householdMembers(真实同住成员数组，每项name,role,occupation,ageYears；孤身则空数组),startingWealth(非负数字)。家庭必须由本次世界与问答原创推演，禁止固定内容库。三项的label+parents+location组合不得相同。资料：${JSON.stringify({world:r.generatedWorld,birthMethod:r.birthMethod,birthAnswers:r.birthAnswers})}`);return validateFamilies(extractJson(text),r.template.id)}
 async generateRandomFamily(r:FamilyGenerationRequest){const cards=await this.generateFamilies(r);return cards[cryptoRandomIndex(cards.length)]}
 async generateTalents(r:TalentGenerationRequest){const text=await this.chat('你是人生模拟器天赋生成器。仅返回合法JSON字符串数组。',`严格生成恰好10个互不重复的中文天赋字符串，必须同时符合生成世界、已选家庭与角色，不得使用固定天赋池。资料：${JSON.stringify({world:r.generatedWorld,family:r.family,character:r.character})}`);return validateTalents(extractJson(text))}
 async generateBirthNarrative(c:NarrativeContext){const text=await this.chat('你是中文文学叙事者。只返回出生篇章正文，不要标题、JSON或代码块。',`请写一段具体、有氛围且与设定一致的出生叙事（约500-800字），不得声称自己是AI。资料：${JSON.stringify(c)}`);if(!text.trim())throw new Error('AI 未生成出生叙事');return text.trim().replace(/^```(?:text|markdown)?\s*/i,'').replace(/\s*```$/,'')}
 async generateLifeEvent(c:LifeEventGenerationContext):Promise<PendingLifeEvent>{
  const s=c.state, stageGuide={新生儿:'家庭、健康、成长',幼儿:'家庭与探索',童年:'学校与家庭',少年:'同伴与学业',青年:'教育、职业、关系',成年:'事业、家庭、健康',老年:'健康、回忆、传承'}[s.lifeStage];
  const brief={world:{name:c.world.name,overview:c.world.overview,dangers:c.world.dangers,socialStructure:c.world.socialStructure},character:c.character,advanceMonths:c.advanceMonths,state:{ageMonths:s.ageMonths,stage:s.lifeStage,progression:s.progression,progressionTiers:c.world.progressionSystem?.tiers,attributeLabels:s.attributeLabels,attributes:s.attributes,vitals:s.vitals,money:{personal:s.personalMoney,family:s.familyWealth},location:s.currentLocation,family:s.familyMembers,social:s.socialCharacters,facts:s.facts},recentTimeline:s.timeline.slice(-10).map(x=>({title:x.title,description:x.description}))};
  const text=await this.chat('你是人生事件导演。只返回严格合法JSON对象，不得解释。效果只能使用指定白名单字段，不得输出对象路径。',`本次时间跨越为 ${c.advanceMonths} 个月。生成一个能代表这整个时期最关键变化、适龄且不重复近期内容的事件；不要把它假装成只发生在某一天。阶段重点：${stageGuide}。返回字段 category,title,description,participants,choices；choices严格2-4项，每项含id,label,intent,effects。普通事件严禁attempt_breakthrough。若上下文pendingBreakthrough=true，则必须生成突破事件，2-4个策略且每项恰好含一个attempt_breakthrough(risk为safe/balanced/reckless，bonus可为-0.3..0.3)，策略风险应有差异。effects白名单：modify_attribute(attribute为8项之一,amount -10..10), modify_vital(vital为health/energy/mood/stress,amount -20..20), modify_money(account personal/family,amount -100000..100000), modify_progression(amount -20..100), attempt_breakthrough(risk,bonus), modify_relationship(memberId,amount -20..20), change_location(location), add_character(character含name/role等), update_character(memberId及允许字段), kill_character(memberId,reason), kill_player(reason), add_fact(fact)。每个选择给出合理建议效果；跨越较长时段可建议合理的修炼/成长进度，修仙、武侠、魔法尤其相关；普通生活事件不可无理由突破，进度量应结合相邻层跨度。不得创造任意状态路径。上下文：${JSON.stringify(brief)}`);
  return validateLifeEvent(extractJson(text),s,c.advanceMonths)
 }
 async generateEventOutcomeNarrative(c:LifeEventGenerationContext,event:PendingLifeEvent,choice:PendingLifeEvent['choices'][number],resolution:EventResolution){const text=await this.chat('你是简洁的中文人生叙事者。只返回结果正文。',`用80-180字叙述选择后的结果，不新增未提供的数值效果。资料：${JSON.stringify({world:c.world.name,age:c.state.ageMonths,event,choice,actualResolution:resolution})}`);if(!text.trim())throw new Error('AI 未生成结果叙事');return text.trim()}
}
