import {useEffect,useMemo,useState} from 'react';
import {getWorldDefinition,worlds} from './data/worlds';
import {generateFamilyCards,generateTalentOffer,isThemeSelectionValid,resolveSelectedFamilyId,toggleTalentSelection,toggleThemeSelection} from './domain/generators';
import {LocalNarrativeProvider,narrateBirth} from './narrative/provider';
import {clearState,loadState,saveState} from './storage/gameStorage';
import {LocalWorldGenerationProvider} from './world-generation/provider';
import type {BirthMethod,CharacterProfile,FamilyCard,SimulatorState,ThemeMode,WorldId} from './types';
const steps=[['welcome','欢迎'],['world-select','模板'],['world-detail','详情'],['theme-select','主题'],['world-generating','推演'],['world-confirm','世界'],['birth-method','投胎'],['family-selection','家庭'],['character-create','角色'],['talent-select','天赋'],['birth-result','出生'],['life-home','人生']] as const;
const methods:Record<BirthMethod,string>={random:'随机投胎','three-choice':'三选一',custom:'自定义投胎','ai-qa':'AI 问答投胎'};
const initial=():SimulatorState=>({customWorldPrompt:'',themeTags:[],selectedThemes:[],familyCards:[],character:{name:'',gender:'未定',personality:''},offeredTalents:[],selectedTalents:[],birthNarrative:'',currentStep:'welcome'});
function restoreState(): SimulatorState {
 const saved = loadState();
 if (!saved) return initial();
 const base = initial();
 return {
  ...base,
  ...saved,
  themeTags: Array.isArray(saved.themeTags) ? saved.themeTags : [],
  selectedThemes: Array.isArray(saved.selectedThemes) ? saved.selectedThemes : [],
  familyCards: Array.isArray(saved.familyCards) ? saved.familyCards : [],
  offeredTalents: Array.isArray(saved.offeredTalents) ? saved.offeredTalents : [],
  selectedTalents: Array.isArray(saved.selectedTalents) ? saved.selectedTalents : [],
  character: { ...base.character, ...saved.character },
  currentStep: saved.generatedWorld ? saved.currentStep : saved.currentStep === 'welcome' ? 'welcome' : 'world-select',
 };
}
function Family({card,selected,onClick}:{card:FamilyCard;selected:boolean;onClick:()=>void}){return <button className={`family-card ${selected?'selected':''}`} onClick={onClick}><div className="family-card__head"><h3>{card.label}</h3><span>{card.socialClass}</span></div><p>{card.parents}</p><p>出生地：{card.location}</p><p>优势：{card.advantages.join(' · ')}</p><p>风险：{card.risks.join(' · ')}</p></button>}
export function App(){
 const [theme,setTheme]=useState<ThemeMode>('light'); const [s,setS]=useState<SimulatorState>(restoreState); const [busy,setBusy]=useState(false); const provider=useMemo(()=>new LocalWorldGenerationProvider(),[]);
 const template=s.worldId?getWorldDefinition(s.worldId,s.customWorldPrompt):null; const family=s.familyCards.find(x=>x.id===s.selectedFamilyId); const patch=(p:Partial<SimulatorState>)=>setS(x=>({...x,...p}));
 useEffect(()=>{if(window.matchMedia?.('(prefers-color-scheme: dark)').matches)setTheme('dark')},[]); useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]); useEffect(()=>saveState(s),[s]);
 async function openDetail(){if(!template)return; setBusy(true); const tags=await provider.generateThemeTags(template,s.customWorldPrompt); patch({themeTags:tags,selectedThemes:[],generatedWorld:undefined,currentStep:'world-detail'});setBusy(false)}
 async function generateWorld(){if(!template||!isThemeSelectionValid(s.selectedThemes))return;patch({currentStep:'world-generating'});try{const generatedWorld=await provider.generateWorld({template,selectedThemes:s.selectedThemes,customPrompt:s.customWorldPrompt});patch({generatedWorld,currentStep:'world-confirm'})}catch{patch({currentStep:'theme-select'})}}
 function families(m:BirthMethod){if(!template||!s.generatedWorld)return;const cards=generateFamilyCards(template.id,s.customWorldPrompt,s.generatedWorld);patch({birthMethod:m,familyCards:cards,selectedFamilyId:resolveSelectedFamilyId(cards,m),currentStep:'family-selection'})}
 async function birth(){if(!template||!s.generatedWorld||!family||!s.birthMethod)return;setBusy(true);const birthNarrative=await narrateBirth(new LocalNarrativeProvider(),{template,generatedWorld:s.generatedWorld,family,character:s.character,talents:s.selectedTalents,birthMethod:s.birthMethod});patch({birthNarrative,currentStep:'birth-result'});setBusy(false)}
 return <div className="app-shell"><div className="ambient ambient-a"/><div className="ambient ambient-b"/><header className="topbar panel"><div><p className="eyebrow">AI LIFE SIMULATOR · WORLD FORGE</p><h1>浮生 · AI 人生模拟器</h1></div><div className="toolbar"><button className="ghost-button" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?'深色':'日间'}</button><button className="ghost-button" onClick={()=>{clearState();setS(initial())}}>重新开始</button></div></header><main className="layout"><aside className="sidebar panel"><div className="stepper">{steps.map(([k,l],i)=>{const ci=steps.findIndex(x=>x[0]===s.currentStep);return <div key={k} className={`step-pill ${i<=ci?'is-active':''} ${k===s.currentStep?'is-current':''}`}><span>{i+1}</span><strong>{l}</strong></div>})}</div><section className="summary-box"><h2>旅程摘要</h2><ul><li><span>模板</span><strong>{template?.name??'未选择'}</strong></li><li><span>主题</span><strong>{s.selectedThemes.join('、')||'待选择'}</strong></li><li><span>AI 世界</span><strong>{s.generatedWorld?.name??'待推演'}</strong></li><li><span>投胎</span><strong>{s.birthMethod?methods[s.birthMethod]:'未选择'}</strong></li></ul></section></aside><section className="content panel">
 {s.currentStep==='welcome'&&<section className="hero-grid"><div><p className="eyebrow">每一次推演，都是一个新世界</p><h2>先告诉 AI 你向往怎样的舞台。</h2><p className="lead">选择世界模板和主题，AI 将推演时代、社会、家庭、成长与危险，再由你确认并投胎其中。</p><button className="primary-button" onClick={()=>patch({currentStep:'world-select'})}>开始生成世界</button></div><div className="hero-card"><h3>AI 世界铸造流程</h3><ol><li>选择世界模板</li><li>挑选 3—5 个主题</li><li>AI 推演完整世界</li><li>确认世界并选择家庭</li><li>开启独一无二的人生</li></ol></div></section>}
 {s.currentStep==='world-select'&&<section><div className="section-head"><div><p className="eyebrow">WORLD TEMPLATE</p><h2>选择世界模板</h2><p className="lead">模板只提供创作方向，并不是固定世界。</p></div></div><div className="world-grid">{(Object.keys(worlds) as WorldId[]).map(id=><button className={`world-card ${s.worldId===id?'selected':''}`} key={id} onClick={()=>patch({worldId:id})}><div className="world-card__top"><h3>{worlds[id].name}</h3><span>{worlds[id].eraTag}</span></div><p>{worlds[id].subtitle}</p></button>)}</div>{s.worldId==='custom'&&<div className="custom-world-box"><label>补充你的世界构想</label><textarea rows={3} value={s.customWorldPrompt} onChange={e=>patch({customWorldPrompt:e.target.value})}/></div>}<div className="footer-actions"><button disabled={!s.worldId||busy} className="primary-button" onClick={openDetail}>{busy?'AI 正在理解模板…':'查看模板详情'}</button></div></section>}
 {s.currentStep==='world-detail'&&template&&<section><div className="section-head"><div><p className="eyebrow">TEMPLATE DETAIL</p><h2>{template.name}</h2><p className="lead">{template.description}</p></div><button className="ghost-button" onClick={()=>patch({currentStep:'world-select'})}>更换模板</button></div><div className="detail-grid">{template.detailSections.map(x=><article className="info-card" key={x.title}><h3>{x.title}</h3><p>{x.content}</p></article>)}</div><div className="footer-actions"><button className="primary-button" onClick={()=>patch({currentStep:'theme-select'})}>生成主题标签</button></div></section>}
 {s.currentStep==='theme-select'&&<section><div className="section-head"><div><p className="eyebrow">THEME SIGNALS</p><h2>选择 3—5 个主题</h2><p className="lead">AI 会让这些主题相互作用，塑造世界的核心矛盾与生活纹理。</p></div><span className="counter-badge">已选 {s.selectedThemes.length}/5 · 至少 3 个</span></div><div className="theme-grid">{s.themeTags.map(x=><button key={x} className={`theme-chip ${s.selectedThemes.includes(x)?'selected':''}`} onClick={()=>patch({selectedThemes:toggleThemeSelection(s.selectedThemes,x)})}>{x}</button>)}</div><div className="selection-hint">{s.selectedThemes.length<3?`还需选择 ${3-s.selectedThemes.length} 个主题`:s.selectedThemes.length===5?'已达上限，可取消后更换':'可以继续选择，或开始推演'}</div><div className="footer-actions"><button className="ghost-button" disabled={busy} onClick={async()=>{if(!template)return;setBusy(true);try{patch({themeTags:await provider.generateThemeTags(template,s.customWorldPrompt),selectedThemes:[]})}finally{setBusy(false)}}}>{busy?'AI 正在生成…':'重新生成标签'}</button><button className="primary-button" disabled={!isThemeSelectionValid(s.selectedThemes)} onClick={generateWorld}>让 AI 推演世界</button></div></section>}
 {s.currentStep==='world-generating'&&<section className="generation-stage"><div className="ai-orb"><span/></div><p className="eyebrow">AI WORLD SIMULATION</p><h2>AI 正在推演世界…</h2><p className="lead">正在建立社会秩序、出生地区、成长路径与命运冲突</p><div className="generation-lines"><i/><i/><i/></div></section>}
 {s.currentStep==='world-confirm'&&s.generatedWorld&&<section><div className="section-head"><div><p className="eyebrow">AI GENERATED WORLD</p><h2>{s.generatedWorld.name}</h2><p className="lead">{s.generatedWorld.overview}</p></div><span className="counter-badge">AI 生成世界</span></div><div className="world-result-hero"><strong>{s.generatedWorld.selectedThemes.join(' × ')}</strong><p>{s.generatedWorld.eraBackground}</p></div><div className="detail-grid generated-details">{([['社会结构',s.generatedWorld.socialStructure],['核心矛盾',s.generatedWorld.coreConflict],['生活环境',s.generatedWorld.livingEnvironment],['成长路径',s.generatedWorld.growthPaths],['爱情婚姻',s.generatedWorld.loveMarriageRules],['家庭结构',s.generatedWorld.familyStructure],['主要危险',s.generatedWorld.dangers],['寿命规则',s.generatedWorld.lifespan],['出生地区',s.generatedWorld.birthRegions.join('、')]] as const).map(x=><article className="info-card" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="footer-actions"><button className="ghost-button" onClick={()=>patch({currentStep:'theme-select'})}>返回调整主题</button><button className="ghost-button" onClick={generateWorld}>重新推演</button><button className="primary-button" onClick={()=>patch({currentStep:'birth-method'})}>确认世界，开始投胎</button></div></section>}
 {s.currentStep==='birth-method'&&<section><p className="eyebrow">BIRTH MODE</p><h2>选择投胎方式</h2><p className="lead">你的家庭将基于 AI 生成世界的地区与社会结构创建。</p><div className="method-grid">{(Object.keys(methods) as BirthMethod[]).map(m=><button className="method-card" onClick={()=>families(m)} key={m}><h3>{methods[m]}</h3><p>{m==='random'?'交给命运自动选择家庭。':m==='three-choice'?'从三个不同起点中选择。':'MVP 中以家庭候选卡承载，后续可接入更深度 AI。'}</p></button>)}</div></section>}
 {s.currentStep==='family-selection'&&<section><h2>选择你的家庭</h2><div className="family-grid">{s.familyCards.map(c=><Family key={c.id} card={c} selected={c.id===s.selectedFamilyId} onClick={()=>s.birthMethod!=='random'&&patch({selectedFamilyId:c.id})}/>)}</div><div className="footer-actions"><button disabled={!s.selectedFamilyId} className="primary-button" onClick={()=>patch({currentStep:'character-create'})}>确认家庭</button></div></section>}
 {s.currentStep==='character-create'&&<section><h2>创建角色</h2><div className="form-grid"><label><span>姓名</span><input value={s.character.name} onChange={e=>patch({character:{...s.character,name:e.target.value}})}/></label><label><span>性别</span><select value={s.character.gender} onChange={e=>patch({character:{...s.character,gender:e.target.value as CharacterProfile['gender']}})}>{['女','男','非二元','未定'].map(x=><option key={x}>{x}</option>)}</select></label><label className="full-width"><span>性格底色</span><textarea rows={4} value={s.character.personality} onChange={e=>patch({character:{...s.character,personality:e.target.value}})}/></label></div><div className="footer-actions"><button disabled={!s.character.name.trim()||!s.character.personality.trim()} className="primary-button" onClick={()=>template&&patch({offeredTalents:generateTalentOffer(template.id,s.customWorldPrompt,s.generatedWorld),selectedTalents:[],currentStep:'talent-select'})}>生成天赋候选</button></div></section>}
 {s.currentStep==='talent-select'&&<section><div className="section-head"><h2>选择 3 个天赋</h2><span className="counter-badge">{s.selectedTalents.length}/3</span></div><div className="talent-grid">{s.offeredTalents.map(x=><button className={`talent-chip ${s.selectedTalents.includes(x)?'selected':''}`} key={x} onClick={()=>patch({selectedTalents:toggleTalentSelection(s.selectedTalents,x)})}>{x}</button>)}</div><div className="footer-actions"><button disabled={s.selectedTalents.length!==3||busy} className="primary-button" onClick={birth}>{busy?'AI 正在书写…':'生成出生篇章'}</button></div></section>}
 {s.currentStep==='birth-result'&&s.generatedWorld&&family&&<section><p className="eyebrow">BIRTH CHAPTER</p><h2>{s.character.name}的第一声啼哭</h2><article className="narrative-card"><h3>{s.generatedWorld.name}</h3><p>{s.birthNarrative}</p></article><div className="result-grid"><article className="info-card"><h3>家庭</h3><p>{family.label} · {family.location}</p></article><article className="info-card"><h3>天赋</h3><p>{s.selectedTalents.join('、')}</p></article><article className="info-card"><h3>世界主题</h3><p>{s.selectedThemes.join('、')}</p></article></div><div className="footer-actions"><button className="primary-button" onClick={()=>patch({currentStep:'life-home'})}>进入人生</button></div></section>}
 {s.currentStep==='life-home'&&<section><p className="eyebrow">LIFE BEGINS</p><h2>人生首页（MVP）</h2><div className="life-home-grid"><article className="info-card accent"><h3>{s.character.name}</h3><p>{s.generatedWorld?.name}</p></article><article className="info-card"><h3>当前状态</h3><p>0 岁 · 新生儿 · 世界已开始运转</p></article><article className="info-card"><h3>自动保存</h3><p>开局已保存在本地，可刷新恢复。</p></article></div></section>}
 </section></main></div>}
export default App;
